### PR TITLE
Quick fix for slideshow downloading

### PR DESCRIPTION
**Pull request by ltm7725**
Since index.js always runs through getIdVideo(), makes it so the program doesn't quit out when the current post is a slideshow

### CODE REVIEW

**Comment by timmbobb** [comment]
Does this allow the downloading of slides or just prevent it from crashing when it attempts to?

**Comment by ltm7725** [comment]
It downloads the slideshows successfully

**Comment by timmbobb** [comment]
Ah cool. I was trying to figure out how to fix that in my forked version but hadn't quite got to it

**Comment by timmbobb** [comment]
You seem pretty knowledgeable, do you have any idea about the stuff mentioned in issue #31

**Comment by n0l3r** [comment]
thank u

**Pull request merged**
